CREATE TABLE IF NOT EXISTS rounds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  image_path TEXT NOT NULL,
  building_name TEXT NOT NULL,
  floor TEXT NOT NULL,
  hint TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_name TEXT NOT NULL,
  total_score INTEGER NOT NULL,
  round_details TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
